[package]
name = "rogue"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
image = "0.25.9"
log = "0.4.28"
regex = "1.12.2"
sdl2 = { version = "0.38.0" , features = []}
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.33"
uuid = {  version = "1.18.1", features = ["v4"] }